[package]
name = "rust-rest"
version = "0.1.0"
authors = ["Alexandr Semenov <aleksandr.semenov@gs-labs.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.1"