---
kind: Service
apiVersion: v1
metadata:
  name: {{ template "rra.fullname" . }}
  labels:
    app: {{ template "rra.fullname" . }}
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: rra
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  selector:
    app: {{ template "rra.fullname" . }}
    component: rra
  ports:
  - protocol: TCP
    port: {{ .Values.rra.servicePort }}
    targetPort: {{ .Values.rra.port }}
