name: rra
home: https://github.com/CrownBerry/rust-rest
version: 0.2.2
appVersion: 0.2.2
description: Rust REST API service Helm chart
sources:
  - https://github.com/CrownBerry/rust-rest
maintainers:
  - name: Alexandr Koeln
    email: koelnfrei@gmail.com
